@startuml branching-parallel-development

"Main branch" -> "Dev 1\nbugfix/fix-data-cleaning-error": Dev 1 creates a new branch\nto fix data cleaning error
"Main branch" -> "Dev 2\nfeature/add-variance-plot": Dev 2 creates a new branch\nto create a variance plot
"Dev 1\nbugfix/fix-data-cleaning-error" -> "Dev 1\nbugfix/fix-data-cleaning-error": Dev 1 adds and/or changes\nfiles to fix error in data cleaning
"Dev 2\nfeature/add-variance-plot" -> "Dev 2\nfeature/add-variance-plot": Dev 2 adds and/or changes\nfiles to create variance plot
"Dev 1\nbugfix/fix-data-cleaning-error" -> "Main branch": After PR and review,\nchanges are merged into main
"Dev 1\nbugfix/fix-data-cleaning-error" -> "Dev 1\nbugfix/fix-data-cleaning-error" !! : Delete
"Dev 2\nfeature/add-variance-plot" -> "Main branch": After PR and review,\nchanges are merged into main
"Dev 2\nfeature/add-variance-plot" -> "Dev 2\nfeature/add-variance-plot" !! : Delete

@enduml 
