
@startuml file-tracking-in-git

"Unmodified" -> "Modified": Save new file or\nedited file
"Modified" -> "Staged": Phase 1 of commit:\nAdd file to staging area
"Staged" -> "Unmodified": Phase 2 of commit:\nCommit file

@enduml 