@startuml github-flow

title GitHub Flow
"Main branch" -> "New branch": Create new branch from main
"New branch" -> "New branch": Add and/or change files\n to implement e.g., new feature
"New branch" --> "Main branch": Create pull request
"New branch" -> "New branch": Review
"New branch" --> "New branch": Implement suggested\n changes (if any)
"New branch" -> "Main branch": When approved, merge\nthe new branch with main
"New branch" -> "New branch" !! : Delete

@enduml