# Pre-course tasks {#sec-pre-course}

{{< include ../includes/_wip.qmd >}}

In order to participate in this course, you must complete everything in
this pre-course tasks section and finish with **completing the
[survey]()** at the end. These tasks are designed to make it easier for
everyone to start the course with everything set up. For some of the
tasks, you might not understand why you need to do them, but you will
likely understand why once the course begins.

Depending on your skills and knowledge, these tasks could take between
**3-5 hrs to finish**, so we suggest planning a full day to complete
them. Depending on your institution and how they handle installing
software on work computers, you also might have to contact IT *very
early* to make sure everything is properly installed and setup.

## Summary of tasks

Here's a quick overview of the tasks you need to do. Specific details
about them are found as you work through the tasks.

1.  Install a version of Git that is as updated as possible. For some
    people, depending on their institution, this task can take the
    **longest amount of time** because you have to contact your IT to
    install these packages.
2.  TODO: Add more tasks
3.  Read the syllabus (@sec-syllabus).
4.  Read the [Code of
    Conduct](https://guides.rostools.org/conduct.html).
5.  Complete the pre-course [survey](): This survey is pretty quick,
    maybe \~10 minutes. There will be some bits from the tasks that you
    will need to paste into this survey.

Check each section for exact details on completing these tasks.

## Learning objective

In general, these pre-course tasks are meant to help prepare you for the
course and make sure everything is setup properly so the first session
runs smoothly. However, some of these tasks are meant for learning as
well as for general setup, so we have defined the following learning
objectives for this page:

1.  TODO: List objectives

## Reading the course website

We will explain this a bit during the course, but read this to start
learning how the website is structured and how to read certain things.
Specifically, there are a few "syntax" type formatting of the text in
this website to be aware of:

-   Folder names always end with a `/`, for example `data/` means the
    data folder.
-   Reading tasks always start with a statement "Reading task" and are
    enclosed in a "callout block". Read within this block. We will
    usually go over the section again to reinforce the concepts and
    address any questions.

## Installing the latest programs

The first thing to do is to install these programs. You may already have
some of them installed and if you do, please make sure that they are at
least the minimum versions listed below. If not, you will need to update
them.

TODO: Link to Guides for installation?

Check out the online book [Happy Git with
R](https://happygitwithr.com/), especially the "Why Git" section, for an
understanding on why we are teaching Git. Windows users tend to have
more trouble with installing Git than macOS or Linux users. See the
section on [Installing Git for
Windows](https://happygitwithr.com/install-git.html#install-git-windows)
for help.

> *A note to those who have or use work laptops with restrictive
> administrative privileges*: You may encounter problems installing
> software due to administrative reasons (e.g. you don't have permission
> to install things). Git is not a commonly used software for some
> organizations, so you may not have it installed and you *will* need to
> ask IT to install it. We *require* it for the course, so please make
> sure to give IT enough time to be able to install it for you prior to
> the course.

*If you encounter any troubles during these pre-course tasks*, try as
best as you can to complete the task and then let us know about the
issues in the pre-course survey. If you continue having problems,
indicate on the survey that you need help and we can try to book a quick
video call to fix the problem. Otherwise, you can come to the course
15-20 minutes earlier to get help.

## TODO: Next section

## Course basics

If you haven't read the syllabus, **please read it now**. Read over what
the course will cover, what we expect you to learn by the end of it, and
what our basic assumptions are about who you are and what you already
know. At the end of this section, we'll ask you a few questions to see
if you understand what you'll learn in the course.

One goal of the course is to teach about openness, and true to our
mission, we practice what we preach. The course material is publicly
accessible (all on this website) and [openly licensed](/LICENSE.md) so
you can (re-)use it for free! The material is organized in the order
that we will cover it in the course.

We have a [Code of Conduct](https://guides.rostools.org/conduct.html).
If you haven't read it, **read it now**. The survey involves a question
about Conduct. We want to make sure this course is a supportive and safe
environment for learning, so this Code of Conduct is quite important.

You're almost done. Please fill out the pre-course survey to finish this
section, either [at this link]().

See you at the course!
