# Group project work {#sec-group-project}


To maximize how much you learn and how much you will retain, during the last
session of the course you and one or two others will take what you learn in the
course and apply it as a team to collaboratively complete a small, hopefully fun
project. **The project will be to create a collection of recipes for meals that
you and your teammate enjoy eating the most right now.** You can decide how many recipes to include, but at minimum, you should have one recipe for each person.

<!-- TODO: Include other options for projects? -->

## Specific tasks

You will be collaborating as a team using Markdown files, Git, and GitHub to collaborate together on the project.
These are the tasks you need to complete:

1. Decide on one person being the "admin" who will create (and own) a GitHub repository for the project.
2. If you're the admin, add your other team member(s) as a collaborator on the GitHub repository.
1. Using the contributor workflow, each teammate will create a `README.md` file and write a basic introduction of themselves in the README file. Then create a pull request. Once one and create a pull request.some basic agreemnts on working together in the README (at the same time, so we can trigger a merge conflict)
1. Create issues of which recipes to include (one per person in the group) + an introduction to the cookbook (i.e., the README)
2. Apply the contributor workflow by selecting a recipe (e.g., a dessert), create a branch for it, write it out in Markdown, and make a PR
3. Apply the reviewer workflow by reviewing one of the other's recipes on GitHub with suggestions and feedback? (i.e., request changes) - like add spices; a header for ingredients, etc.?
4. Go back to contributor workflow by going through the suggestions and include or reject them. Ask for a new review from the reviewer (and continue this back and forth until the reviewer approves)
5. Then apply the "admin" workflow and merge.

## Quick "checklist" for a good project

-   Used Git and is on GitHub.
- Created and closed GitHub Issues.
-   Used Markdown for writing text.
- Used a commit message style (like Conventional Commits).
-   README has some basic details like collaboration agreements.
-   Added some basic challenges and general experiences in the
    discussion section.
-   Generated a final HTML file from a single `report.qmd` Quarto file.

## Expectations for the project

What we expect you to do for the group project:

-   Use Git and GitHub throughout your work.
-   Work collaboratively as a group and share responsibilities and
    tasks.
-   Use as much of what we covered in the course to practice what you
    learned.

What we don't expect:

-   Complicated analysis or coding. The simpler it is, the easier is to
    for you to do the coding and understand what is going on. It also
    helps us to see that you've practiced what you've learned.
-   Clever or overly concise code. Clearly written and readable code is
    *always* better than clever or concise code. Keep it simple and
    understandable!

Essentially, the group project is a way to reinforce what you learned
during the course, but in a more relaxed and collaborative setting.
