name: Build and deploy website

on:
  push:
    branches: main

jobs:
  build-deploy-docs:
    uses: rostools/.github/.github/workflows/build-website.yml@main
    secrets: 
      netlify-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
